name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: shopeasy-app
  NODE_VERSION: '18.x'
  RESOURCE_GROUP: shopeasy-rg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm install

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Configure App Service
      run: |
        # Set environment variables
        az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --settings @(
          "SQL_USER=shopeasyadmin",
          "SQL_PASSWORD=Rohit#124",
          "SQL_SERVER=shopeasy-server.database.windows.net",
          "SQL_DATABASE=shopeasy-db",
          "STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=shopeasystorage1;AccountKey=2YHc1qo1IP4n0uzbFQOwHOvw1UcgQ1LO/+hfK97FYnUyf6w7hYhBGI8eB0WwlxDu3oq036OVcFbf+AStZQ3lJA==;EndpointSuffix=core.windows.net",
          "STORAGE_CONTAINER_NAME=product-images",
          "JWT_SECRET=shopeasy-secure-jwt-key-2024",
          "PORT=3000",
          "APP_URL=https://shopeasy-app-cgajx6audwa0ee.centralindia-01.azurewebsites.net",
          "SCM_DO_BUILD_DURING_DEPLOYMENT=true",
          "WEBSITE_NODE_DEFAULT_VERSION=~18"
        )

        # Configure Node.js
        az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --linux-fx-version "NODE|18-lts"

        # Configure startup command
        az webapp config set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --startup-file "npm install && npm start"

    - name: Deploy to Azure
      run: |
        # Create a zip file excluding unnecessary files
        zip -r app.zip . -x "node_modules/*" ".git/*" ".github/*" "*.zip"

        # Deploy the application
        az webapp deploy --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --src-path app.zip --type zip 